<?php

namespace EpreuveBundle\Repository;

/**
 * EpreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuveRepository extends \Doctrine\ORM\EntityRepository
{
}
