athlete_index:
    path:     /
    defaults: { _controller: "EpreuveBundle:Athlete:index" }
    methods:  GET

athlete_show:
    path:     /{id}/show
    defaults: { _controller: "EpreuveBundle:Athlete:show" }
    methods:  GET

athlete_new:
    path:     /new
    defaults: { _controller: "EpreuveBundle:Athlete:new" }
    methods:  [GET, POST]

athlete_edit:
    path:     /{id}/edit
    defaults: { _controller: "EpreuveBundle:Athlete:edit" }
    methods:  [GET, POST]

athlete_delete:
    path:     /{id}/delete
    defaults: { _controller: "EpreuveBundle:Athlete:delete" }
    methods:  DELETE
